name: unicore-cms
user: ubuntu
buildscript: sideloader/deploy.sh
postinstall: sideloader/postinstall.sh
pip:
 - gunicorn
 - pyramid
 - pyramid_chameleon
 - pyramid_debugtoolbar
 - pyramid_beaker
 - python-memcached
 - webtest
 - waitress
 - cornice
 - cffi
 - pygit2
 - praekelt-python-gitmodel
 - unicore-gitmodels
dependencies:
 - python-yaml
 - cmake
