name: unicore-cms
user: ubuntu
buildscript: sideloader/deploy.sh
postinstall: sideloader/postinstall.sh
pip:
 - gunicorn
 - pyramid
 - pyramid_chameleon
 - pyramid_debugtoolbar
 - waitress
dependencies:
 - python-yaml
