name: unicore-cms
user: ubuntu
buildscript: sideloader/deploy.sh
postinstall: sideloader/postinstall.sh
pip:
 - gunicorn
 - pyramid
 - pyramid_chameleon
 - pyramid_debugtoolbar
 - waitress
 - cffi
 - pygit2
 - praekelt-python-gitmodel
dependencies:
 - python-yaml
 - libgit2-dev
