language: python
python:
  - "2.7"
services:
  - elasticsearch
install:
  - pip install -r requirements-dev.txt --use-wheel
  - pip install -r requirements.txt --use-wheel
  - pip install -e . --use-wheel
script:
  - find ./cms -name '*.py' | xargs pep8
  - find ./cms -name '*.py' | xargs pyflakes
  - py.test cms
after_success:
  - coveralls
deploy:
  provider: pypi
  user: Praekelt
  password:
    secure: EA5FqGREb4eAPa+lf7/qtAFQW8eCvvQA6RTbnpwvPhYRxvFtudi0v/r668dX08LEwsIlqJ4X02XjMJNBU2rn3VGvsgStJPBnhkf5BptbbiCdVM+T9FhNN2jLMUk4fmFjrniHt/4a/biKgTMDgWek7xhbaI3gBMQkKY1MFhZRnjI=
  on:
    tags: true
