language: python
python:
  - "2.7"
sudo: false
cache:
  directories:
    - $HOME/.cache/pip
services:
  - elasticsearch
install:
  - pip install --upgrade pip
  - pip install -r requirements-dev.txt
  - pip install -r requirements.txt
  - pip install -e .
script:
  - find ./cms -name '*.py' | xargs pep8
  - find ./cms -name '*.py' | xargs pyflakes
  - py.test cms --cov ./cms
after_success:
  - coveralls
deploy:
  provider: pypi
  user: Praekelt
  password:
    secure: ImBeoAGBekGH2+7bSTkbPiE7aN4ZkA7KuELK4TrD+CHNDZLmInTi/S7T+PSEbMLt3wC1qvhLaZhnCKeuRQKjhu3C5tjZY0ekDPYWsv2dB5vFsXAsBcB9YCS3nY8MCdT1uACZdGrOB1ze+dD/CtYLoaiXKY7yJix9pbexR+1nF2Y=
  on:
    tags: true
    all_branches: true
