language: python
python:
  - "2.7"
install:
  - ./utils/install_libgit2.sh
  - pip install -r requirements.txt --use-wheel
  - pip install -r requirements-dev.txt --use-wheel
  - pip install -e . --use-wheel
script:
  - find ./cms -name '*.py' | xargs pep8
  - LIBGIT2=$VIRTUAL_ENV ./run-tests.sh
after_success:
  - coveralls
