language: python
python:
  - "2.7"
install:
  - pip install git+git://github.com/smn/elastic-git.git#egg=elastic-git
  - pip install -r requirements-dev.txt --use-wheel
  - pip install -e . --use-wheel
script:
  - find ./cms -name '*.py' | xargs pep8
  - find ./cms -name '*.py' | xargs pyflakes
  - py.test cms
after_success:
  - coveralls
