language: python
python:
  - "2.7"
install:
  - ./utils/install_libgit2.sh
  - "pip install coveralls coverage --use-wheel"
  - "pip install -r requirements.txt --use-wheel"
script:
  - LIBGIT2=$VIRTUAL_ENV coverage run --source=cms setup.py test
after_success:
  - coveralls
